name: haskell-quickbooks
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2018 Author name here
license: BSD3
github: githubuser/haskell-quickbooks
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- hpack
- text
- bytestring
- aeson
- containers
- mtl
- fast-logger
- hoauth2
- lens
- wreq
- http-client
- http-client-tls
- uri-bytestring
- string-conv
- safe

library:
  source-dirs: src
  exposed-modules:
  - Lib
